export const tnc_header = 'In order to use the app, you need to accept terms and condition';

export const tnc = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non erat vel est sollicitudin efficitur in non augue. Nunc purus nisi, varius et nibh in, euismod congue ante. Donec elit lectus, euismod quis est sit amet, dictum eleifend nunc. Nunc at cursus purus. Sed dignissim massa sed enim vulputate, sed commodo lectus pharetra. Nunc non blandit ex. Pellentesque mollis consectetur lectus sed hendrerit. Proin blandit pretium quam scelerisque tincidunt. Proin sodales venenatis lectus eu vestibulum. Morbi aliquam elementum justo, at faucibus lacus facilisis sit amet. Proin ut dictum risus. Fusce faucibus vel ipsum a dapibus.

Phasellus eget vehicula urna. Curabitur dictum lorem lorem. Mauris rutrum non diam eget euismod. Suspendisse eget justo pretium, hendrerit metus vitae, elementum purus. Praesent id sapien varius, vehicula velit quis, porta lectus. Donec dignissim blandit fermentum. Etiam et nunc sit amet lorem ultricies semper. Curabitur suscipit tortor nunc. Ut scelerisque faucibus congue. Vestibulum eu nisi nec mi sodales placerat id id elit. Suspendisse interdum in metus et euismod. Ut consectetur, justo sit amet iaculis condimentum, justo quam consectetur elit, eget vehicula diam leo quis risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

In vulputate ornare nisl, sed laoreet magna aliquet a. Nulla euismod facilisis urna, id tincidunt augue fringilla eget. Quisque leo magna, luctus at dictum eget, euismod congue ipsum. Pellentesque dignissim lobortis pulvinar. Pellentesque vulputate, eros in semper ornare, nisl dui viverra sem, vel tempus justo ipsum ac dolor. Pellentesque suscipit dui vel massa commodo, id luctus lacus pretium. Sed tortor lorem, tincidunt in dui a, dictum tempor mi. Integer fermentum tincidunt nulla, ut accumsan tortor egestas non. Aenean dignissim vel augue ut placerat. Pellentesque blandit fermentum elit, vitae pulvinar enim ultrices iaculis. Pellentesque ut luctus eros, condimentum porttitor ipsum. Quisque quis ex eu nunc consequat mollis et et ex. Nam congue dui id ligula molestie, eget mattis urna pharetra. Sed quis lacinia velit.

Aenean ullamcorper, massa sit amet ultricies consequat, lectus dolor hendrerit lacus, at fermentum ex lacus eget mi. Nulla ipsum nibh, posuere sit amet nunc nec, varius sollicitudin augue. Quisque et dolor eget orci vestibulum cursus. Integer viverra diam tellus, dignissim pharetra risus fermentum nec. Mauris sollicitudin dolor ullamcorper metus porttitor vehicula. Fusce ac massa et purus vestibulum accumsan ut suscipit erat. Fusce et vehicula nibh. Nullam eu tincidunt augue. Nullam a viverra sapien. Ut auctor elit tortor, at vestibulum eros luctus at. Nullam sagittis placerat pretium. Vestibulum gravida eu ipsum quis porta. Integer ornare dui elit, a ullamcorper velit lacinia eu. Ut ut elit nec urna tristique interdum in non eros. Sed sed risus ac lectus accumsan aliquet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Quisque ultricies ligula nec nisl malesuada dictum. Nam sed erat laoreet, euismod eros vel, viverra sapien. Proin facilisis eros non mauris bibendum vulputate. Nulla eget erat ac felis aliquet mollis. Suspendisse sed lacinia sapien. Proin gravida porta neque eget placerat. Vestibulum scelerisque sem sed orci ullamcorper iaculis. In ut metus ut est maximus lacinia sit amet ac purus. Aenean dignissim ultrices augue, eu tincidunt lectus sagittis nec. Maecenas nec facilisis neque.`;
